[font]
size = 14
normal = { family = "CommitMono Nerd Font" }

[window]
option_as_alt = "OnlyLeft"
decorations = "None"

# moonfly theme for Alacritty
#
# Upstream: github.com/bluz71/vim-moonfly-colors

[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#1e2024'
foreground = '#a1a3a8'

# Normal colors
[colors.normal]
black = '#27272a'
blue = '#5e7fdd'
cyan = '#97c3fa'
green = '#90b99f'
magenta = '#e29eca'
red = '#d45d9e'
white = '#c9c7cd'
yellow = '#f0ea2d'

# Bright colors
[colors.bright]
black = '#353539'
blue = '#a7b3dd'
cyan = '#6de6fc'
green = '#a8fc8d'
magenta = '#eb4cce'
red = '#ca72de'
white = '#c9c7cd'
yellow = '#f7f48d'

[colors.cursor]
cursor = "#8e8e8e"
text = "#080808"

[colors.selection]
background = "#b2ceee"
text = "#080808"
