# vim:ft=ansible:
name: dev

windows:
  - gmscore:
      layout: main-vertical
      panes:
        - main:
          - hgd gmscore
          - vim
        - other:
          - hgd gmscore

  - experimental:
      layout: main-vertical
      panes:
        - main:
          - hgd experimental
          - vim
        - other:
          - hgd experimental

  - notes:
      panes:
        - main:
          - hgd notes
          - cd ../company/users/cnieves/
          - vim ~/zettelkasten/Todo.md
  - dotfiles:
      layout: main-vertical
      panes:
        - main:
          - cd ~/dotfiles
          - vim
        - other:
          - cd ~/dotfiles
