# vim:ft=ansible:
name: dev

windows:
  - gmscore:
      layout: main-horizontal
      panes:
        - main:
          - hgd gmscore
          - vim
        - other:
          - hgd gmscore

  - experiments:
      layout: main-horizontal
      panes:
        - main:
          - hgd experiments
          - vim
        - other:
          - hgd experiments

  - notes:
      panes:
        - main:
          - cd ~/zettelkasten
          - vim ~/zettelkasten/Todo.md

  - dotfiles:
      layout: main-horizontal
      panes:
        - main:
          - cd ~/dotfiles
          - vim
        - other:
          - cd ~/dotfiles
