# vim:ft=ansible:
name: dev

windows:
  - gmscore:
      layout: main-horizontal
      panes:
        - main:
        - other:

  - experiments:
      layout: main-horizontal
      panes:
        - main:
        - other:

  - critique:
      layout: main-horizontal
      panes:
        - main:
        - other:

  - dotfiles:
      layout: main-horizontal
      panes:
        - main:
        - other:
